# .github/workflows/test-connection.yml

name: Test Snowflake Connection

# This allows to run the workflow manually from the Actions tab
on:
  workflow_dispatch:

jobs:
  test-snowflake-connection:
    name: Test Connection to Snowflake
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install and configure the Snowflake CLI
      - name: Setup Snow CLI
        uses: snowflakedb/snowflake-cli-action@v1.5
          
      # Step 2: Run commands using the now-installed Snow CLI
      - name: Run test queries
        env:
          # Provide all credentials to the environment for this step
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.CICD_DEMO_DB }}
          SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
          SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
        run: |
          echo "Verifying Snow CLI installation..."
          snow --version

          echo "Testing connection and running queries..."
          snow sql -q "SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE()"
          snow sql -q "SELECT 'Connection successful!' as TEST_MESSAGE"
