# .github/workflows/test-connection.yml

name: Test Snowflake Connection

# This allows to run the workflow manually from the Actions tab
on:
  workflow_dispatch:

jobs:
  test-snowflake-connection:
    name: Test Connection to Snowflake
    runs-on: ubuntu-latest

    steps:
      # Use the official SnowSQL action
      - name: Run simple query on Snowflake
        uses: snowflakedb/snowflake-cli-action@v1.5
        env:
          
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.CICD_DEMO_DB }} # Corrected to match your setup
              
          SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
          SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }} # Note the different name

        run: |
          # Use the 'snow' command to run queries
          echo "Testing connection and context..."
          snow sql -q "SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE()"

          echo "Running a simple query..."
          snow sql -q "SELECT 1 + 1 as RESULT"
